language: node_js
node_js:
  - 12
​
services:
  - docker
​
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
​
# Scripts to be run such as tests
before_script:
  - echo "no tests"
​
script:
  # print the version for logging
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed samuelshorun/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user samuelshorun/udagram-api-user:v1
  - docker build -t reverseproxy ./reverseproxy
  - docker tag reverseproxy samuelshorun/reverseproxy:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend samuelshorun/udagram-frontend:v1
​
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samuelshorun/udagram-api-feed:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samuelshorun/udagram-api-user:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samuelshorun/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samuelshorun/udagram-frontend:v1