apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: docker.io/samuelshorun/udagram-api-feed:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2000Mi
          requests:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    feed: udagram-api-feed