apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/samuelshorun/udagram-api-user:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2000Mi
          requests:
            cpu: 500m


---
apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
spec:
  ports:
  - port: 8080
    protocol: 
    targetPort: 8080
  selector:
    app: udagram-api-user